### ISSUE TITLE
Task has too many dependencies

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#236]
Apparently, 100 is the limit for the number of tasks:

https://firefox-ci-tc.services.mozilla.com/tasks/ZOGs-Db0TNqG6gvn_3cLbA/runs/0/logs/public/logs/live.log

```
[task 2023-10-27T19:34:47.687Z] 2023-10-27 19:34:47,687 - INFO - Generated 16 tasks for kind evaluate-quantized
[task 2023-10-27T19:34:47.690Z] 2023-10-27 19:34:47,690 - INFO - Generated 1 tasks for kind export
[task 2023-10-27T19:34:47.713Z] 2023-10-27 19:34:47,713 - INFO - Generated 16 tasks for kind evaluate-teacher-ensemble
[task 2023-10-27T19:34:47.714Z] 2023-10-27 19:34:47,714 - ERROR - Error loading tasks for kind all:
[task 2023-10-27T19:34:47.714Z] Traceback (most recent call last):
[task 2023-10-27T19:34:47.714Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 310, in _run
[task 2023-10-27T19:34:47.714Z]     new_tasks = kind.load_tasks(
[task 2023-10-27T19:34:47.714Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 76, in load_tasks
[task 2023-10-27T19:34:47.714Z]     tasks = [
[task 2023-10-27T19:34:47.714Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 76, in <listcomp>
[task 2023-10-27T19:34:47.714Z]     tasks = [
[task 2023-10-27T19:34:47.714Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/transforms/task.py", line 1339, in check_run_task_caches
[task 2023-10-27T19:34:47.714Z]     for task in tasks:
[task 2023-10-27T19:34:47.714Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/transforms/task.py", line 1275, in check_task_dependencies
[task 2023-10-27T19:34:47.715Z]     raise Exception(
[task 2023-10-27T19:34:47.715Z] Exception: task all/all-lt-en has too many dependencies (113 > 99)
[task 2023-10-27T19:34:47.715Z] Traceback (most recent call last):
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/main.py", line 669, in action_callback
[task 2023-10-27T19:34:47.715Z]     return trigger_action_callback(
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/actions/registry.py", line 337, in trigger_action_callback
[task 2023-10-27T19:34:47.715Z]     cb(Parameters(**parameters), graph_config, input, task_group_id, task_id)
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/checkouts/src/taskcluster/translations_taskgraph/actions/train.py", line 302, in train_action
[task 2023-10-27T19:34:47.715Z]     taskgraph_decision({"root": graph_config.root_dir}, parameters=parameters)
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/decision.py", line 102, in taskgraph_decision
[task 2023-10-27T19:34:47.715Z]     full_task_json = tgg.full_task_graph.to_json()
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 170, in full_task_graph
[task 2023-10-27T19:34:47.715Z]     return self._run_until("full_task_graph")
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 424, in _run_until
[task 2023-10-27T19:34:47.715Z]     k, v = next(self._run)
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 310, in _run
[task 2023-10-27T19:34:47.715Z]     new_tasks = kind.load_tasks(
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 76, in load_tasks
[task 2023-10-27T19:34:47.715Z]     tasks = [
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 76, in <listcomp>
[task 2023-10-27T19:34:47.715Z]     tasks = [
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/transforms/task.py", line 1339, in check_run_task_caches
[task 2023-10-27T19:34:47.715Z]     for task in tasks:
[task 2023-10-27T19:34:47.715Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/transforms/task.py", line 1275, in check_task_dependencies
[task 2023-10-27T19:34:47.715Z]     raise Exception(
[task 2023-10-27T19:34:47.715Z] Exception: task all/all-lt-en has too many dependencies (113 > 99)
[taskcluster 2023-10-27 19:34:47.902Z] === Task Finished ===
```

**Comment by bhearsum** [comment]
Just to re-cap what was discussed on Slack:
- A quick, hacky fix for this is:
```
diff --git a/taskcluster/ci/all/kind.yml b/taskcluster/ci/all/kind.yml
index 5599e3f..db1a389 100644
--- a/taskcluster/ci/all/kind.yml
+++ b/taskcluster/ci/all/kind.yml
@@ -7,19 +7,16 @@ loader: taskgraph.loader.transform:loader
 
 transforms:
     - taskgraph.transforms.task_context
     - taskgraph.transforms.from_deps
     - taskgraph.transforms.task:transforms
 
 kind-dependencies:
     - export
-    - evaluate
-    - evaluate-quantized
-    - evaluate-teacher-ensemble
 
 tasks:
     all:
         description: Dummy task that ensures all parts of training pipeline will run
         attributes:
             stage: all
             src_locale: "{src_locale}"
             trg_locale: "{trg_locale}"
```

...which has the downside of not running `evaluate` tasks by default

- Our usual workaround for this is to add `dummy` tasks in-between things like `all` and the actual tasks it depends on. (You can see an example of this on https://firefox-ci-tc.services.mozilla.com/tasks/UCVDKd2LTQ2l8XqPrMNKAg)

- We can look into getting the limit removed at the platform level, but I'm not sure how viable that is at the moment.

**Comment by gabrielBusta** [comment]
Not this again :( reminds me of the l10n in gecko. Maybe we can parametrize this on our deployment?

**Comment by bhearsum** [comment]
https://github.com/mozilla/firefox-translations-training/pull/237 may do the trick here, actually. I was thinking we'd need dummy tasks, but because this is a leaf task, I think just chunking it will do the trick.

**Comment by marco-c** [comment]
@bhearsum should we close this?
