### ISSUE TITLE
TARGET not found

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#259]
When I run
```bash
make run TARGET=merge_corpus
```
(or any target)

taken from https://github.com/mozilla/firefox-translations-training/blob/main/docs/snakemake.md

I see
```log
echo "Running with config configs/config.prod.yml and profile local"
source ../mambaforge/etc/profile.d/conda.sh ; conda activate ; conda activate snakemake
chmod +x profiles/local/*
export SNAKEMAKE_OUTPUT_CACHE=../cache; snakemake \
  --profile=profiles/local \
  --configfile configs/config.prod.yml \
  merge_corpus
Running with config configs/config.prod.yml and profile local
Traceback (most recent call last):
  File "/mambaforge/envs/snakemake/bin/snakemake", line 10, in <module>
    sys.exit(main())
  File "/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 2755, in main
    success = snakemake(
  File "/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 500, in snakemake
    update_config(overwrite_config, load_configfile(f))
  File "/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/io.py", line 1618, in load_configfile
    config = _load_configfile(configpath)
  File "/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/io.py", line 1583, in _load_configfile
    obj = open(configpath_or_obj, encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'merge_corpus'
Makefile:69: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by eu9ene** [comment]
Interesting, dry-run works fine on my local machine `make dry-run TARGET=merge_corpus`. You can also try using absolute path to the expected output file.

**Comment by AmitMY** [comment]
Tried that, without success.

You can see my exact machine config here:
https://github.com/sign-language-processing/signbank-plus/blob/main/signbank_plus/nmt/bergamot/docker/Dockerfile

The `RUN make test TARGET=train_vocab` fails (and I also tried with the file path). not sure what is the difference.

**Comment by AmitMY** [comment]
Anything else I can check? running the `test` until `train_vocab` inside my docker build will accelerate running experiments for me
