### ISSUE TITLE
opuscleaner fails to pip install

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#292]
From [a recent PR](https://firefox-ci-tc.services.mozilla.com/tasks/HGA6hgcuTGiLFKAjUuj3Tg/runs/0/logs/live/public/logs/live.log):
```
[task 2023-12-11T14:11:35.151Z] Building wheels for collected packages: sacremoses, opuscleaner
[task 2023-12-11T14:11:35.151Z]   Building wheel for sacremoses (setup.py): started
[task 2023-12-11T14:11:35.484Z]   Building wheel for sacremoses (setup.py): finished with status 'done'
[task 2023-12-11T14:11:35.487Z]   Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=79c9665f6124a686bb06caf5351973d2c33879e234bd146d715e1bf599e00d07
[task 2023-12-11T14:11:35.487Z]   Stored in directory: /tmp/pip-ephem-wheel-cache-7ltzqd1n/wheels/00/24/97/a2ea5324f36bc626e1ea0267f33db6aa80d157ee977e9e42fb
[task 2023-12-11T14:11:35.490Z]   Building wheel for opuscleaner (pyproject.toml): started
[task 2023-12-11T14:11:35.639Z]   Building wheel for opuscleaner (pyproject.toml): finished with status 'error'
[task 2023-12-11T14:11:35.645Z]   error: subprocess-exited-with-error
[task 2023-12-11T14:11:35.645Z]   
[task 2023-12-11T14:11:35.645Z]   × Building wheel for opuscleaner (pyproject.toml) did not run successfully.
[task 2023-12-11T14:11:35.645Z]   │ exit code: 1
[task 2023-12-11T14:11:35.645Z]   ╰─> [18 lines of output]
[task 2023-12-11T14:11:35.645Z]       Traceback (most recent call last):
[task 2023-12-11T14:11:35.645Z]         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
[task 2023-12-11T14:11:35.645Z]           main()
[task 2023-12-11T14:11:35.645Z]         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
[task 2023-12-11T14:11:35.645Z]           json_out['return_val'] = hook(**hook_input['kwargs'])
[task 2023-12-11T14:11:35.645Z]         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
[task 2023-12-11T14:11:35.645Z]           return _build_backend().build_wheel(wheel_directory, config_settings,
[task 2023-12-11T14:11:35.645Z]         File "/tmp/pip-build-env-u1do9rsi/overlay/local/lib/python3.10/dist-packages/hatchling/build.py", line 58, in build_wheel
[task 2023-12-11T14:11:35.645Z]           return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
[task 2023-12-11T14:11:35.645Z]         File "/tmp/pip-build-env-u1do9rsi/overlay/local/lib/python3.10/dist-packages/hatchling/builders/plugin/interface.py", line 155, in build
[task 2023-12-11T14:11:35.645Z]           artifact = version_api[version](directory, **build_data)
[task 2023-12-11T14:11:35.645Z]         File "/tmp/pip-build-env-u1do9rsi/overlay/local/lib/python3.10/dist-packages/hatchling/builders/wheel.py", line 405, in build_standard
[task 2023-12-11T14:11:35.645Z]           for included_file in self.recurse_included_files():
[task 2023-12-11T14:11:35.645Z]         File "/tmp/pip-build-env-u1do9rsi/overlay/local/lib/python3.10/dist-packages/hatchling/builders/plugin/interface.py", line 177, in recurse_included_files
[task 2023-12-11T14:11:35.645Z]           yield from self.recurse_forced_files(self.config.get_force_include())
[task 2023-12-11T14:11:35.645Z]         File "/tmp/pip-build-env-u1do9rsi/overlay/local/lib/python3.10/dist-packages/hatchling/builders/plugin/interface.py", line 231, in recurse_forced_files
[task 2023-12-11T14:11:35.645Z]           raise FileNotFoundError(msg)
[task 2023-12-11T14:11:35.645Z]       FileNotFoundError: Forced include not found: /tmp/pip-install-xjad9haa/opuscleaner_72a0b73a911d4f26ae32f4562fcf4b1e/frontend/dist
[task 2023-12-11T14:11:35.645Z]       [end of output]
[task 2023-12-11T14:11:35.645Z]   
[task 2023-12-11T14:11:35.645Z]   note: This error originates from a subprocess, and is likely not a problem with pip.
[task 2023-12-11T14:11:35.645Z]   ERROR: Failed building wheel for opuscleaner
```

**Comment by bhearsum** [comment]
@ahal pointed out that the error involves `hatchling`, which is [the build system for opuscleaner](https://github.com/hplt-project/OpusCleaner/blob/main/pyproject.toml#L2). That's had [two recent releases](https://pypi.org/project/hatchling/#history), and I suspect that we always use the latest one when building opuscleaner. This is most likely an upstream issue. (There might be a way for us to pin the hatchling version, but I'm not sure how off the top of my head.)

**Comment by bhearsum** [comment]
Getting them to release and using that (instead of pinning to a source revision) might help - then we'd avoid their build system altogether.

**Comment by AmitMY** [comment]
They have now released.
