### ISSUE TITLE
Snakemake dry run is broken

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#363]
```
[task 2024-01-12T19:21:59.577Z] Start the dry run
[task 2024-01-12T19:21:59.578Z] echo "Dry run with config configs/config.prod.yml and profile local"
[task 2024-01-12T19:21:59.578Z] source /builds/worker/artifacts/mambaforge/etc/profile.d/conda.sh ; conda activate ; conda activate snakemake
[task 2024-01-12T19:21:59.578Z] export SNAKEMAKE_OUTPUT_CACHE=/builds/worker/artifacts/mambaforge; snakemake \
[task 2024-01-12T19:21:59.578Z]   --profile=profiles/local \
[task 2024-01-12T19:21:59.578Z]   --configfile configs/config.prod.yml \
[task 2024-01-12T19:21:59.578Z]   -n \
[task 2024-01-12T19:21:59.578Z]   
[task 2024-01-12T19:21:59.579Z] Dry run with config configs/config.prod.yml and profile local
[task 2024-01-12T19:22:00.049Z] Traceback (most recent call last):
[task 2024-01-12T19:22:00.049Z]   File "/builds/worker/artifacts/mambaforge/envs/snakemake/bin/snakemake", line 10, in <module>
[task 2024-01-12T19:22:00.049Z]     sys.exit(main())
[task 2024-01-12T19:22:00.049Z]   File "/builds/worker/artifacts/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 2377, in main
[task 2024-01-12T19:22:00.049Z]     parser = get_argument_parser()
[task 2024-01-12T19:22:00.049Z]   File "/builds/worker/artifacts/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 1382, in get_argument_parser
[task 2024-01-12T19:22:00.049Z]     lp_solvers = pulp.list_solvers(onlyAvailable=True)
[task 2024-01-12T19:22:00.050Z] AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?
```

**Comment by gregtatum** [comment]
Shouldn't CI catch this?
