### ISSUE TITLE
Bicleaner-AI is not using GPUs

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#388]
https://firefox-ci-tc.services.mozilla.com/tasks/groups/KRXRJ_lTSWWrv0F20lORCQ
https://firefox-ci-tc.services.mozilla.com/tasks/groups/KsSrCXPtRzCie4wkejInsA

It seems bicleaner-ai is not using GPUs.

**Comment by eu9ene** [comment]
Tensorflow warnings:

```
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:48.424303: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[task 2024-01-19T23:54:25.821Z] To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:48.553085: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:48.553153: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:49.184503: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:49.184703: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:49.184715: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.422098: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.422720: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.422949: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.423135: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.423321: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.466756: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: fetches/cuda-toolkit/lib64:fetches/cuda-toolkit:
[task 2024-01-19T23:54:25.821Z] 2024-01-19 23:09:52.467159: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[task 2024-01-19T23:54:25.821Z] Skipping registering GPU devices...

```

**Comment by eu9ene** [comment]
ok, `/tasks/task_170605347564765/fetches/cuda-toolkit/bin$ ./nvcc --version` gives me

```
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

Tensorflow version is `tensorflow==2.11.1` and it only supports CUDA 11.2. See [this table](https://www.tensorflow.org/install/source#gpu) and [bicleaner readme](https://github.com/bitextor/bicleaner-ai/tree/master#tensorflow).

So we should downgrade cuda to 11.2. It is also being used by Marian so we should probably add another toolchain with a different version.

**Comment by eu9ene** [comment]
@bhearsum @gabrielBusta I think I see the way to fix it but I might need your help here

**Comment by bhearsum** [comment]
I see that `LD_LIBRARY_PATH` is relative (eg: `LD_LIBRARY_PATH=fetches/cuda-toolkit/lib64:fetches/cuda-toolkit`), so I suspect the working directory is changing at some point. Prepending that with `$TASK_WORKDIR` will get you the full directory path - which I imagine will fix this. I don't think you'll be able to put it in the `env` definition though, because it will not be interpreted. Instead, I suggest moving the env variables definitions to [the bicleaner command section](https://github.com/mozilla/firefox-translations-training/blob/bc616e7e088a746557391b8094545d9356553fcc/taskcluster/kinds/bicleaner/kind.yml#L98), similar to [what we do for evaluate](https://github.com/mozilla/firefox-translations-training/blob/d5f4291f167df1619fb386f847419604fb108ee0/taskcluster/kinds/evaluate/kind.yml#L80).

**Comment by eu9ene** [comment]
I'll give it a try but the files it's looking for are not there, I checked. @marco-c suggested to also try using the latest Tensoflow (which supports cuda 12) and see if it's compatible with the bicleaner code. It seems there was no reason to limit the version of tensorflow, it might be just a legacy thing. I'll check this too.

**Comment by eu9ene** [comment]
With tensorflow 2.15:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bicleaner-ai-classify", line 5, in <module>
    from bicleaner_ai.bicleaner_ai_classifier import main
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bicleaner_ai/bicleaner_ai_classifier.py", line 23, in <module>
    from .classify import classify, argument_parser, load_metadata
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bicleaner_ai/classify.py", line 18, in <module>
    from .util import check_positive, check_positive_or_zero, check_positive_between_zero_and_one, logging_setup, get_model
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bicleaner_ai/util.py", line 17, in <module>
    from .models import DecomposableAttention, Transformer, BCXLMRoberta
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bicleaner_ai/models.py", line 1, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist 
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.xlm_roberta.modeling_tf_xlm_roberta because of the following error (look up to see its traceback):
No module named 'keras.engine'
```
