### ISSUE TITLE
Upgrade to BicleanerAI 3.0

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#528]
https://github.com/bitextor/bicleaner-ai/blob/v3.0.0/CHANGELOG.md

The release includes new multilingual models. We can try using `large` ones. see https://github.com/bitextor/bicleaner-ai/blob/v3.0.0/docs/training/multilingual.md#performance

**Comment by eu9ene** [comment]
`pip-compile` doesn't lock the requirements for `bicleaner-ai==3.0.1`:

```
pip-compile -r pipeline/bicleaner/requirements/bicleaner-ai.in
  ERROR: Cannot install -r pipeline/bicleaner/requirements/bicleaner-ai.in (line 1) because these package versions have conflicting dependencies.
Discarding bicleaner-hardrules==2.7.0 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 17)) to proceed the resolution
  ERROR: Cannot install -r pipeline/bicleaner/requirements/bicleaner-ai.in (line 1) because these package versions have conflicting dependencies.
Discarding protobuf==3.19.6 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 109)) to proceed the resolution
  ERROR: Cannot install -r pipeline/bicleaner/requirements/bicleaner-ai.in (line 1) because these package versions have conflicting dependencies.
Discarding transformers==4.26.0 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 203)) to proceed the resolution
  ERROR: Cannot install -r pipeline/bicleaner/requirements/bicleaner-ai.in (line 1) because these package versions have conflicting dependencies.
Discarding huggingface-hub==0.11.1 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 59)) to proceed the resolution
  ERROR: Cannot install bicleaner-ai because these package versions have conflicting dependencies.
Discarding fastspell==0.5 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 29)) to proceed the resolution
  ERROR: Cannot install bicleaner-ai because these package versions have conflicting dependencies.
Discarding tokenizers==0.13.3 (from -r pipeline/bicleaner/requirements/bicleaner-ai.txt (line 190)) to proceed the resolution
  ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
  ERROR: Could not find a version that satisfies the requirement cyhunspell<=2.0.3,>=2.0.2 (from fastspell) (from versions: 1.0.1, 1.1.0, 1.1.3, 1.1.3.post1, 1.1.4, 1.2.0, 1.2.1, 1.3.0, 1.3.2, 1.3.3, 1.3.4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 316, in _backjump
    name, candidate = broken_state.mapping.popitem()
KeyError: 'dictionary is empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 434, in resolve
    success = self._backjump(causes)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in _backjump
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('cyhunspell<=2.0.3,>=2.0.2'), parent=LinkCandidate('https://files.pythonhosted.org/packages/95/23/e837768b8bd548e1b3b607198fd8d179ffe2f9d68ad867192185cf1ae7b4/fastspell-0.11-py3-none-any.whl (from https://pypi.org/simple/fastspell/) (requires-python:>=3.8)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/dist-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
  File "/usr/local/lib/python3.10/dist-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for cyhunspell<=2.0.3,>=2.0.2
```
